<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AttendanceRecordsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttendanceRecordsRepository extends EntityRepository
{
	

	public function findEmpAndDate($id)
	{
	$setNull = null;
	$date = new \DateTime('now');
	$query = $this->createQueryBuilder('AR')
       ->select('IDENTITY(AR.empId)','AR.timeIn', 'AR.timeOut')
       ->andWhere('AR.empId = :id')
       ->setParameter('id', $id)
       ->andWhere('AR.timeIn > :timeIn')
       ->setParameter('timeIn', $date->format('Y-m-d 00:00:00'))
	   ->getQuery();

	   return $query->getResult();
	}
	/*public function findTimeOut($id)
	{
        $date = new \DateTime('now');
        $timeStart = $date->format('Y-m-d 00:00:00');
        $timeEnd = $date->format('Y-m-d 23:59:59');

	  $query = $this->createQueryBuilder('AR')
       ->select('IDENTITY(AR.empId)','AR.timeIn', 'AR.timeOut')
       ->andWhere('AR.empId = :id')
       ->setParameter('id', $id)

       ->andWhere('AR.timeIn >= :timeIn1')
       ->setParameter('timeIn1', $timeStart)
       ->andWhere('AR.timeIn <= :timeIn2')
       ->setParameter('timeIn2', $timeEnd)
	 ->getQuery();
       
       $result = $query->getResult();
	 return $result;
	}*/
	public function searchByDate($id)
      {
            $startDate = new \DateTime($id);
            $endDate = new \DateTime($id);
            $query = $this->createQueryBuilder('AR')
            ->select(
                  
                  'AR.id as exId',
                  'empId.firstName as firstName',
                  'empId.lastName as lastName',
                  'empId.middleName as middleName',
                  'empId.contactDetails as contactDetails',
                  'empId.address as address',
                  'empId.emergencyName as emergencyName',
                  'empId.emergencyRelation as emergencyRelation',
                  'empId.emergencyContact as emergencyContact',
                  'empId.id as valId',
                  'AR.timeIn as timeIn',
                  'AR.numberOfEdits as numberOfEdits', 
                  'AR.timeOut as timeOut')
            ->join('AR.empId', 'empId')
            ->andWhere('AR.timeIn > :startDate')
            ->setParameter('startDate', $startDate->format('Y-m-d 00:00:00'))
            ->andWhere('AR.timeIn < :endDate')
            ->setParameter('endDate', $endDate->format('Y-m-d 23:59:59'))
            ->orderBy('AR.timeIn', 'ASC')
            ->getQuery();

         return $query->getResult();
      }

      public function SearchDateFromTo($id, $id2)
	{
		$startDate = new \DateTime($id.'00:00:00');
            $endDate = new \DateTime($id2.'23:59:59');
            $query = $this->createQueryBuilder('AR')
            ->select(
                  'AR.id as exId',
                  'empId.firstName as firstName',
                  'empId.lastName as lastName',
                  'empId.middleName as middleName',
                  'empId.contactDetails as contactDetails',
                  'empId.address as address',
                  'empId.emergencyName as emergencyName',
                  'empId.emergencyRelation as emergencyRelation',
                  'empId.emergencyContact as emergencyContact',
                  'empId.id as valId',
                  'AR.timeIn as timeIn', 
                  'AR.timeOut as timeOut')
            ->join('AR.empId', 'empId')
            ->andWhere('AR.timeIn BETWEEN :startDate AND :endDate')
            ->setParameter('startDate', $startDate)
            ->setParameter('endDate', $endDate)
            ->orderBy('AR.timeIn', 'ASC')
            ->getQuery();

	   return $query->getResult();
	}

      public function findAllRecords()
      {
            $query = $this->createQueryBuilder('AR')
            ->select('empId.firstName as firstName','empId.lastName as lastName','empId.id as valId','AR.timeIn as timeIn', 'AR.timeOut as timeOut')
            ->join('AR.empId', 'empId')
            ->getQuery();

         return $query->getResult();
      }

	public function findEditAttendance($exId)
	{
      $query = $this->createQueryBuilder('AR')
       ->select(
            'IDENTITY(AR.empId)',
            'AR.timeIn', 
            'AR.timeOut',
            'AR.id',
            'empId.firstName as firstName',
            'empId.middleName as middleName',
            'empId.lastName as lastName'
            )

       ->join('AR.empId', 'empId')
       ->andWhere('AR.id = :exId')
       ->setParameter('exId', $exId)
       
      ->getQuery();

      return $query->getResult();
	}

      public function findRecord($id,$tI)
      {
      $date1 = new \DateTime($tI);
      $query = $this->createQueryBuilder('AR')
       ->select('IDENTITY(AR.empId)','AR.timeIn', 'AR.timeOut')
       ->andWhere('AR.empId = :id')
       ->setParameter('id', $id)
       ->andWhere('AR.timeIn BETWEEN :timeIn AND :timeOut')
       ->setParameter('timeIn', $date1->format('Y-m-d 00:00:00'))
       ->setParameter('timeOut', $date1->format('Y-m-d 23:59:59'))
         ->getQuery();

         return $query->getResult();
      }
}
