<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * crudetestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeRepository extends EntityRepository
{
	/*public function findAllOrderByName()
	{
		return $this->findBy(array(), array('firstName' => 'ASC'));
	}*/
	public function showEmployees()
	{
		$query = $this->createQueryBuilder('ER')
       ->select('ER.id','ER.firstName','ER.middleName','ER.lastName', 'ER.dateEmployement')
       ->orderBy('ER.firstName', 'ASC')
	   ->getQuery();

	   return $query->getResult();
	}
	/*
	public function showEmployee($id)
	{
		$query = $this->createQueryBuilder('ER')
       ->select(
       		'ER.id',
       		'ER.firstName',
       		'ER.middleName',
       		'ER.lastName', 
       		'ER.gender',
       		'ER.address',
       		'ER.dob',
       		'ER.dateEmployement',
       		'ER.contactDetails',
       		'ER.emergencyName',
       		'ER.emergencyRelation',
       		'ER.emergencyContact',
       		'ER.status'
       		)
       ->orderBy('ER.firstName', 'ASC')
	   ->getQuery();

	   return $query->getResult();
	}*/


	
}